"""syslog and api table

Revision ID: 3a6091d4d4da
Revises: 
Create Date: 2021-05-04 21:03:34.149664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a6091d4d4da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspaceId', sa.String(length=64), nullable=True),
    sa.Column('workspaceKey', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_settings_workspaceId'), 'api_settings', ['workspaceId'], unique=True)
    op.create_table('syslog_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serverIP', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syslog_settings_serverIP'), 'syslog_settings', ['serverIP'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_syslog_settings_serverIP'), table_name='syslog_settings')
    op.drop_table('syslog_settings')
    op.drop_index(op.f('ix_api_settings_workspaceId'), table_name='api_settings')
    op.drop_table('api_settings')
    # ### end Alembic commands ###
